// <auto-generated />
using EFCore_MVC_CodeFirst.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCore_MVC_CodeFirst.Migrations
{
    [DbContext(typeof(StudentContext))]
    [Migration("20250807103825_OneToManyRelation")]
    partial class OneToManyRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCore_MVC_CodeFirst.Models.Items", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ItemId");

                    b.ToTable("items");
                });

            modelBuilder.Entity("EFCore_MVC_CodeFirst.Models.Students", b =>
                {
                    b.Property<int>("studId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("studId"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("dept")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("studId");

                    b.HasIndex("ItemId");

                    b.ToTable("students");
                });

            modelBuilder.Entity("EFCore_MVC_CodeFirst.Models.Students", b =>
                {
                    b.HasOne("EFCore_MVC_CodeFirst.Models.Items", "items")
                        .WithMany("Students")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("items");
                });

            modelBuilder.Entity("EFCore_MVC_CodeFirst.Models.Items", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
